export const CONTRACT_ADDRESS = "0x199a2b36e9f2B8A561c167190DeD5C82Ed32079C";

// Arc Testnet native USDC
export const USDC_ADDRESS = "0x3600000000000000000000000000000000000000";

export const CONTRACT_ABI = [
  {"type":"constructor","inputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"BURN_ADDRESS","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"acceptBondedPayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"acceptMediatedPayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"claimTimelockedPayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"createBondedPayment","inputs":[{"name":"receiver","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"},{"name":"bondAmount","type":"uint256","internalType":"uint256"},{"name":"termsHash","type":"bytes32","internalType":"bytes32"},{"name":"deadline","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"createMediatedPayment","inputs":[{"name":"receiver","type":"address","internalType":"address"},{"name":"arbiter","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"},{"name":"termsHash","type":"bytes32","internalType":"bytes32"},{"name":"deadline","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"createTimelockedPayment","inputs":[{"name":"receiver","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"},{"name":"acceptanceDelay","type":"uint256","internalType":"uint256"},{"name":"termsHash","type":"bytes32","internalType":"bytes32"},{"name":"deadline","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"declineTimelockedPayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"disputePayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"reclaimExpiredPayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"releasePayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"resolveDispute","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"},{"name":"winner","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"slashBondedPayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"treasury","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"getPayment","inputs":[{"name":"paymentId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"tuple","internalType":"struct ConditionalPayments.Payment","components":[{"name":"sender","type":"address","internalType":"address"},{"name":"receiver","type":"address","internalType":"address"},{"name":"arbiter","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"},{"name":"bondAmount","type":"uint256","internalType":"uint256"},{"name":"deadline","type":"uint256","internalType":"uint256"},{"name":"availableAt","type":"uint256","internalType":"uint256"},{"name":"acceptedAt","type":"uint256","internalType":"uint256"},{"name":"termsHash","type":"bytes32","internalType":"bytes32"},{"name":"pType","type":"uint8","internalType":"enum ConditionalPayments.PaymentType"},{"name":"status","type":"uint8","internalType":"enum ConditionalPayments.Status"},{"name":"receiverAccepted","type":"bool","internalType":"bool"},{"name":"resolvedTo","type":"address","internalType":"address"}]}],"stateMutability":"view"},
  {"type":"function","name":"getPaymentsForReceiver","inputs":[{"name":"receiver","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256[]","internalType":"uint256[]"}],"stateMutability":"view"},
  {"type":"function","name":"getPaymentsForSender","inputs":[{"name":"sender","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256[]","internalType":"uint256[]"}],"stateMutability":"view"}
] as const;

export const ERC20_ABI = [
  { "type": "function", "name": "approve", "inputs": [{ "name": "spender", "type": "address", "internalType": "address" }, { "name": "amount", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "allowance", "inputs": [{ "name": "owner", "type": "address", "internalType": "address" }, { "name": "spender", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "balanceOf", "inputs": [{ "name": "account", "type": "address", "internalType": "address" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "decimals", "inputs": [], "outputs": [{ "name": "", "type": "uint8", "internalType": "uint8" }], "stateMutability": "view" }
] as const;