export const CONTRACT_ADDRESS = "0xD61869BA745f9107291a1b46C3BDc99B41849710";

// Arc Testnet native USDC
export const USDC_ADDRESS = "0x3600000000000000000000000000000000000000";

export const CONTRACT_ABI = [
  { "type": "function", "name": "acceptBondedPayment", "inputs": [{ "name": "paymentId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "createBondedPayment", "inputs": [{ "name": "receiver", "type": "address", "internalType": "address" }, { "name": "token", "type": "address", "internalType": "address" }, { "name": "amount", "type": "uint256", "internalType": "uint256" }, { "name": "bondAmount", "type": "uint256", "internalType": "uint256" }, { "name": "termsHash", "type": "bytes32", "internalType": "bytes32" }, { "name": "deadline", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "paymentId", "type": "uint256", "internalType": "uint256" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "createMediatedPayment", "inputs": [{ "name": "receiver", "type": "address", "internalType": "address" }, { "name": "arbiter", "type": "address", "internalType": "address" }, { "name": "token", "type": "address", "internalType": "address" }, { "name": "amount", "type": "uint256", "internalType": "uint256" }, { "name": "termsHash", "type": "bytes32", "internalType": "bytes32" }, { "name": "deadline", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "paymentId", "type": "uint256", "internalType": "uint256" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "createTimelockedPayment", "inputs": [{ "name": "receiver", "type": "address", "internalType": "address" }, { "name": "token", "type": "address", "internalType": "address" }, { "name": "amount", "type": "uint256", "internalType": "uint256" }, { "name": "challengePeriod", "type": "uint256", "internalType": "uint256" }, { "name": "termsHash", "type": "bytes32", "internalType": "bytes32" }, { "name": "deadline", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "paymentId", "type": "uint256", "internalType": "uint256" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "disputePayment", "inputs": [{ "name": "paymentId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "getPayment", "inputs": [{ "name": "paymentId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "tuple", "internalType": "struct ConditionalPayments.Payment", "components": [{ "name": "sender", "type": "address", "internalType": "address" }, { "name": "receiver", "type": "address", "internalType": "address" }, { "name": "arbiter", "type": "address", "internalType": "address" }, { "name": "token", "type": "address", "internalType": "address" }, { "name": "amount", "type": "uint256", "internalType": "uint256" }, { "name": "bondAmount", "type": "uint256", "internalType": "uint256" }, { "name": "deadline", "type": "uint256", "internalType": "uint256" }, { "name": "challengePeriod", "type": "uint256", "internalType": "uint256" }, { "name": "termsHash", "type": "bytes32", "internalType": "bytes32" }, { "name": "pType", "type": "uint8", "internalType": "enum ConditionalPayments.PaymentType" }, { "name": "status", "type": "uint8", "internalType": "enum ConditionalPayments.Status" }] }], "stateMutability": "view" },
  { "type": "function", "name": "releasePayment", "inputs": [{ "name": "paymentId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "resolveDispute", "inputs": [{ "name": "paymentId", "type": "uint256", "internalType": "uint256" }, { "name": "winner", "type": "address", "internalType": "address" }], "outputs": [], "stateMutability": "nonpayable" }
] as const;